/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWatchlistRouteImport } from './routes/_authenticated/watchlist'
import { Route as AuthenticatedTrendsRouteImport } from './routes/_authenticated/trends'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedNewsRouteImport } from './routes/_authenticated/news'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedCommodityIdRouteImport } from './routes/_authenticated/commodity.$id'
import { Route as ApiPublicHooksEvaluateAlertsRouteImport } from './routes/api/public/hooks/evaluate-alerts'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWatchlistRoute = AuthenticatedWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrendsRoute = AuthenticatedTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNewsRoute = AuthenticatedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommodityIdRoute =
  AuthenticatedCommodityIdRouteImport.update({
    id: '/commodity/$id',
    path: '/commodity/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicHooksEvaluateAlertsRoute =
  ApiPublicHooksEvaluateAlertsRouteImport.update({
    id: '/api/public/hooks/evaluate-alerts',
    path: '/api/public/hooks/evaluate-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/home': typeof AuthenticatedHomeRoute
  '/news': typeof AuthenticatedNewsRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/trends': typeof AuthenticatedTrendsRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/commodity/$id': typeof AuthenticatedCommodityIdRoute
  '/api/public/hooks/evaluate-alerts': typeof ApiPublicHooksEvaluateAlertsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/home': typeof AuthenticatedHomeRoute
  '/news': typeof AuthenticatedNewsRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/trends': typeof AuthenticatedTrendsRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/commodity/$id': typeof AuthenticatedCommodityIdRoute
  '/api/public/hooks/evaluate-alerts': typeof ApiPublicHooksEvaluateAlertsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/news': typeof AuthenticatedNewsRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/trends': typeof AuthenticatedTrendsRoute
  '/_authenticated/watchlist': typeof AuthenticatedWatchlistRoute
  '/_authenticated/commodity/$id': typeof AuthenticatedCommodityIdRoute
  '/api/public/hooks/evaluate-alerts': typeof ApiPublicHooksEvaluateAlertsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/alerts'
    | '/dashboard'
    | '/home'
    | '/news'
    | '/pricing'
    | '/profile'
    | '/trends'
    | '/watchlist'
    | '/commodity/$id'
    | '/api/public/hooks/evaluate-alerts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/alerts'
    | '/dashboard'
    | '/home'
    | '/news'
    | '/pricing'
    | '/profile'
    | '/trends'
    | '/watchlist'
    | '/commodity/$id'
    | '/api/public/hooks/evaluate-alerts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/alerts'
    | '/_authenticated/dashboard'
    | '/_authenticated/home'
    | '/_authenticated/news'
    | '/_authenticated/pricing'
    | '/_authenticated/profile'
    | '/_authenticated/trends'
    | '/_authenticated/watchlist'
    | '/_authenticated/commodity/$id'
    | '/api/public/hooks/evaluate-alerts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicHooksEvaluateAlertsRoute: typeof ApiPublicHooksEvaluateAlertsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/watchlist': {
      id: '/_authenticated/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedWatchlistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trends': {
      id: '/_authenticated/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof AuthenticatedTrendsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/news': {
      id: '/_authenticated/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthenticatedNewsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/commodity/$id': {
      id: '/_authenticated/commodity/$id'
      path: '/commodity/$id'
      fullPath: '/commodity/$id'
      preLoaderRoute: typeof AuthenticatedCommodityIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/evaluate-alerts': {
      id: '/api/public/hooks/evaluate-alerts'
      path: '/api/public/hooks/evaluate-alerts'
      fullPath: '/api/public/hooks/evaluate-alerts'
      preLoaderRoute: typeof ApiPublicHooksEvaluateAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedNewsRoute: typeof AuthenticatedNewsRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTrendsRoute: typeof AuthenticatedTrendsRoute
  AuthenticatedWatchlistRoute: typeof AuthenticatedWatchlistRoute
  AuthenticatedCommodityIdRoute: typeof AuthenticatedCommodityIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedNewsRoute: AuthenticatedNewsRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTrendsRoute: AuthenticatedTrendsRoute,
  AuthenticatedWatchlistRoute: AuthenticatedWatchlistRoute,
  AuthenticatedCommodityIdRoute: AuthenticatedCommodityIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicHooksEvaluateAlertsRoute: ApiPublicHooksEvaluateAlertsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
